blank_issues_enabled: false
contact_links:
  - name: Community Discord
    url: https://discord.gg/3MqBvNEyMz
    about: Please ask any and all questions here, and get extra help! If you really need to submit an issue but don't have a GitHub account, you may submit one in the issues forum channel.
