---
name: Super Linter

on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Lint
        uses: github/super-linter@v4
        env:
          # Only check updated code
          DEFAULT_BRANCH: 1.18.x
          VALIDATE_ALL_CODEBASE: false
          VALIDATE_YAML: false
          
          LINTER_RULES_PATH: .github/workflows/
          JAVA_FILE_NAME: sun_checks.xml
